/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function activePreviewAgentCount(): number

export interface PreviewAgentSession {
  sessionId: string
  publicUrl: string
}

export declare function startPreviewAgent(relayUrl: string, name: string, targetUrl: string): Promise<PreviewAgentSession>

export declare function stopPreviewAgent(sessionId: string): Promise<boolean>
