/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function activePreviewAgentCount(): number

export interface PreviewAgentExit {
  closeCode?: number
  closeReason?: string
}

export interface PreviewAgentSession {
  sessionId: string
  publicUrl: string
}

export declare function startPreviewAgent(relayUrl: string, name: string, targetUrl: string): Promise<PreviewAgentSession>

export declare function stopPreviewAgent(sessionId: string): Promise<boolean>

export declare function waitPreviewAgent(sessionId: string): Promise<boolean>

export declare function waitPreviewAgentExit(sessionId: string): Promise<PreviewAgentExit | null>
